"""second migration

Revision ID: f9444ec1f1c2
Revises: e23ac56a4d24
Create Date: 2025-01-10 11:30:06.518905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9444ec1f1c2'
down_revision = 'e23ac56a4d24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
